// fetch-fonts.mjs — one-shot: self-host Source Sans Pro from Google Fonts.
//
// Fetches the Google Fonts stylesheet with a modern UA (so we get woff2),
// keeps only the `latin` and `latin-ext` subsets (all that EN/FR needs),
// downloads each woff2 into assets/webfonts/, and writes the local
// @font-face rules to assets/css/_fonts.generated.css for copy-paste into
// main.css. Re-runnable; overwrites existing files.
//
// Usage: node scripts/fetch-fonts.mjs

import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const fontsDir = join(root, 'assets', 'webfonts');
const outCss = join(root, 'assets', 'css', '_fonts.generated.css');

const FAMILY = 'Source Sans Pro';
const SLUG = 'source-sans-pro';
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);
const CSS_URL =
    'https://fonts.googleapis.com/css?family=Source+Sans+Pro:300italic,600italic,300,600&display=swap';
const UA =
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
    '(KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();

// Each face is preceded by a `/* subset */` comment line.
const blockRe = /\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
const faceRe = {
    style: /font-style:\s*([^;]+);/,
    weight: /font-weight:\s*([^;]+);/,
    src: /url\((https:\/\/[^)]+\.woff2)\)/,
    range: /unicode-range:\s*([^;]+);/
};

const generated = [];
let match;
while ((match = blockRe.exec(css)) !== null) {
    const subset = match[1].trim();
    if (!KEEP_SUBSETS.has(subset)) continue;

    const block = match[2];
    const style = faceRe.style.exec(block)[1].trim();
    const weight = faceRe.weight.exec(block)[1].trim();
    const url = faceRe.src.exec(block)[1];
    const range = faceRe.range.exec(block)[1].trim();

    const file = `${SLUG}-${weight}-${style}-${subset}.woff2`;
    const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
    await mkdir(fontsDir, { recursive: true });
    await writeFile(join(fontsDir, file), buf);
    console.log(`✓ ${file} (${(buf.length / 1024).toFixed(1)} KB)`);

    generated.push(
        `@font-face {\n` +
        `    font-family: '${FAMILY}';\n` +
        `    font-style: ${style};\n` +
        `    font-weight: ${weight};\n` +
        `    font-display: swap;\n` +
        `    src: url('../webfonts/${file}') format('woff2');\n` +
        `    unicode-range: ${range};\n` +
        `}`
    );
}

const header =
    '/* Self-hosted Source Sans Pro (latin + latin-ext).\n' +
    '   Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n\n';
await writeFile(outCss, header + generated.join('\n\n') + '\n');
console.log(`\nWrote ${generated.length} @font-face rules to ${outCss}`);
